# Generated by Django 5.1.7 on 2025-03-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_customer_category_record_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='record',
            name='transaction_type',
            field=models.CharField(default='purchase', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer_category',
            field=models.CharField(default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='record',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
